apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-frontend
  namespace: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-frontend
  template:
    metadata:
      labels:
        app: angular-frontend
    spec:
      containers:
      - name: angular-frontend
        image: asia-east1-docker.pkg.dev/cathay-prob/cathay-prob-frontend/myapp:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: angular-frontend
  namespace: my-app
spec:
  selector:
    app: angular-frontend
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
